version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: nestdb
      POSTGRES_USER: fazt
      POSTGRES_PASSWORD: faztpassword
    ports:
      - 5499:5432
